version: '3'

services:
   app-front:
      build: ./client
      ports:
         - 5001:80

   app-back:
      build: ./server
      ports:
         - 5000:5000


   mongo:
      image: mongo:4.0.4
      ports: 
         - 27017:27017
